name: unaconfig
description: |
  Load your user's config files for your package easily, from multiple sources & formats
version: 0.3.1
homepage: https://github.com/chenasraf/unaconfig_dart

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  file: ^7.0.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9

script_runner:
  scripts:
    - publish: dart format .; dart pub publish
