name: unaconfig
description: "Get user configs for your library with no hassle"
version: 0.0.1
homepage: https://github.com/chenasraf/unaconfig_dart

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  file: ^7.0.0
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.9
